export const BACKEND_URL = 'https://onboarding.art-code.team/'
export const GET_TERMS = 'api/test/v1/search/terms'
export const GET_BRANDS = 'api/test/v1/search/brands_terms'
export const GET_STYLES = 'api/test/v1/search/styles'
export const PARSE_LINK = 'api​/test​/v1​/search​/parse_link'